# Generated by Django 5.0 on 2024-06-06 21:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BlockedCountry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=64)),
                ("iso", models.CharField(max_length=12, unique=True)),
            ],
            options={
                "verbose_name_plural": "blocked countries",
                "db_table": "blocked_country",
            },
        ),
        migrations.CreateModel(
            name="InvalidEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.CharField(max_length=128)),
                ("ip_address", models.CharField(default="0.0.0.0", max_length=128)),
                ("created_date", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "invalid_email",
            },
        ),
        migrations.CreateModel(
            name="BouncedEmail",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bounced_email",
            },
        ),
        migrations.CreateModel(
            name="InvalidSignup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.CharField(max_length=128)),
                ("ip_address", models.CharField(default="0.0.0.0", max_length=128)),
                (
                    "view",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Signup"), (1, "Login"), (2, "Contact Us")]
                    ),
                ),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "blocked_country",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="security.blockedcountry",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "invalid signups",
                "db_table": "invalid_signup",
                "ordering": ["-created_date"],
            },
        ),
    ]
