# Generated by Django 4.1.7 on 2023-04-13 17:55

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlockedCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('iso', models.CharField(max_length=12, unique=True)),
            ],
            options={
                'verbose_name_plural': 'blocked countries',
                'db_table': 'blocked_country',
            },
        ),
        migrations.CreateModel(
            name='InvalidEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=128)),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=128)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invalid_email',
            },
        ),
    ]
