# Generated by Django 4.2.5 on 2024-01-16 19:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('security', '0002_bouncedemail'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvalidCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=128)),
                ('ip_address', models.CharField(default='0.0.0.0', max_length=128)),
                ('view', models.PositiveSmallIntegerField(choices=[(0, 'Signup'), (1, 'Login'), (2, 'Contact Us')])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('blocked_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='security.blockedcountry')),
            ],
            options={
                'verbose_name_plural': 'invalid countries',
                'db_table': 'invalid_country',
                'ordering': ['-created_date'],
            },
        ),
    ]
