# Generated by Django 5.0 on 2024-02-11 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("security", "0003_invalidcountry"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="InvalidCountry",
            new_name="InvalidSignup",
        ),
        migrations.AlterModelOptions(
            name="invalidsignup",
            options={
                "ordering": ["-created_date"],
                "verbose_name_plural": "invalid signups",
            },
        ),
        migrations.AlterModelTable(
            name="invalidsignup",
            table="invalid_signup",
        ),
    ]
