version: 0.0
os: linux
files:
  - source: /
    destination: /scuba/apps/scubamob
hooks:
    ApplicationStart:
      -location: scripts/deploy/install_dependencies.sh
      -location: scripts/deploy/install_db_updates.sh
      -location: scripts/deploy/install_static.sh
       timeout:300
       runas: jello
