[pytest]
DJANGO_SETTINGS_MODULE = scuba.settings
python_files = test*.py
junit_family=xunit2
junit_suite_name = Pytest Tests

addopts =
    --junitxml=test_result.xml
    --cov
    --cov-append
    --cov-config=.coveragerc
    --cov-report xml
