# Generated by Django 6.0.7 on 2026-08-17 16:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('conversation_type', models.CharField(choices=[('DIRECT', 'Direct'), ('GROUP', 'Group'), ('DIVE', 'Dive'), ('TRIP', 'Trip'), ('SHOP', 'Shop'), ('MARKETPLACE', 'Marketplace'), ('SYSTEM', 'System')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_message_at', models.DateTimeField(blank=True, null=True)),
                ('last_message_id', models.CharField(blank=True, max_length=64)),
                ('direct_participants_key', models.CharField(blank=True, editable=False, max_length=80, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_conversations_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_conversation',
            },
        ),
        migrations.CreateModel(
            name='ConversationParticipant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('MEMBER', 'Member'), ('ADMIN', 'Admin'), ('OWNER', 'Owner')], default='MEMBER', max_length=10)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('left_at', models.DateTimeField(blank=True, null=True)),
                ('last_read_message_id', models.CharField(blank=True, max_length=64)),
                ('last_read_at', models.DateTimeField(blank=True, null=True)),
                ('muted', models.BooleanField(default=False)),
                ('archived', models.BooleanField(default=False)),
                ('notifications_enabled', models.BooleanField(default=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='chat.conversation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_participations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'chat_conversation_participant',
            },
        ),
        migrations.AddConstraint(
            model_name='conversation',
            constraint=models.UniqueConstraint(fields=('direct_participants_key',), name='unique_direct_conversation_pair'),
        ),
        migrations.AddConstraint(
            model_name='conversationparticipant',
            constraint=models.UniqueConstraint(fields=('conversation', 'user'), name='unique_conversation_participant'),
        ),
    ]
