# Generated by Django 6.0.7 on 2026-08-14 18:00

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Diveshop",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True, db_index=True, max_length=255)),
                (
                    "lat",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(-90),
                            django.core.validators.MaxValueValidator(90),
                        ],
                    ),
                ),
                (
                    "long",
                    models.DecimalField(
                        decimal_places=9,
                        max_digits=15,
                        validators=[
                            django.core.validators.MinValueValidator(-180),
                            django.core.validators.MaxValueValidator(180),
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "diveshop",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("lat__gte", -90), ("lat__lte", 90)),
                        name="diveshop_lat_in_range",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("long__gte", -180), ("long__lte", 180)),
                        name="diveshop_long_in_range",
                    ),
                ],
            },
        ),
    ]
