# Generated by Django 5.0 on 2024-06-06 21:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AlertingApi",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=128, unique=True)),
                ("value", models.CharField(max_length=128)),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("POST", "POST"),
                            ("GET", "GET"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=128,
                    ),
                ),
            ],
            options={
                "db_table": "alerting_api",
            },
        ),
        migrations.CreateModel(
            name="APIKey",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("WEATHER_API", "Weather API"),
                            ("GOOGLE_MAPS", "Google Maps"),
                        ],
                        db_index=True,
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("value", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "api_key",
            },
        ),
        migrations.CreateModel(
            name="AWSApi",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=128, unique=True)),
                ("value", models.CharField(max_length=128)),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("POST", "POST"),
                            ("GET", "GET"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=128,
                    ),
                ),
            ],
            options={
                "db_table": "aws_api",
            },
        ),
        migrations.CreateModel(
            name="BillingApi",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=128, unique=True)),
                ("value", models.CharField(max_length=128)),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("POST", "POST"),
                            ("GET", "GET"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=128,
                    ),
                ),
            ],
            options={
                "db_table": "billing_api",
            },
        ),
        migrations.CreateModel(
            name="ChatApi",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=128, unique=True)),
                ("value", models.CharField(max_length=128)),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("POST", "POST"),
                            ("GET", "GET"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=128,
                    ),
                ),
            ],
            options={
                "db_table": "chat_api",
            },
        ),
        migrations.CreateModel(
            name="FlagOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("flag", models.CharField(max_length=128)),
                (
                    "instance_type",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "Checkin"), (0, "Review")]
                    ),
                ),
            ],
            options={
                "db_table": "flag_option",
            },
        ),
        migrations.CreateModel(
            name="LogbookApi",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=128, unique=True)),
                ("value", models.CharField(max_length=128)),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("POST", "POST"),
                            ("GET", "GET"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=128,
                    ),
                ),
            ],
            options={
                "db_table": "logbook_api",
            },
        ),
        migrations.CreateModel(
            name="SettingsApi",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(db_index=True, max_length=128, unique=True)),
                ("value", models.CharField(max_length=128)),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("POST", "POST"),
                            ("GET", "GET"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=128,
                    ),
                ),
            ],
            options={
                "db_table": "settings_api",
            },
        ),
        migrations.CreateModel(
            name="SNSSubscriptionRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("message_id", models.CharField(max_length=40, unique=True)),
                ("token", models.TextField()),
                ("topic_arn", models.CharField(max_length=64)),
                ("message", models.CharField(max_length=128)),
                ("subscribe_url", models.TextField()),
                ("timestamp", models.DateTimeField()),
                ("signature_version", models.PositiveSmallIntegerField()),
                ("signature", models.TextField()),
                ("signing_cert_url", models.CharField(max_length=256)),
                ("is_confirmed", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "sns_subscription_requests",
            },
        ),
        migrations.CreateModel(
            name="SystemApi",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("ALERTING_SERVER", "Alerting Server"),
                            ("SETTINGS_SERVER", "Settings Server"),
                            ("AWS_SERVER", "AWS Server"),
                            ("BILLING_SERVER", "Billing Server"),
                            ("CHAT_SERVER", "Chat Server"),
                            ("LOGBOOK_SERVER", "Logbook Server"),
                            ("SETTINGS_SERVER", "Settings Server"),
                            ("API_SERVER", "API Server"),
                            ("AWS_S3_BUCKET", "AWS S3 Bucket"),
                            ("AWS_S3_FILE_DELETE", "AWS S3 File Delete"),
                            ("AWS_S3_FILE_HEADERS", "AWS S3 File Headers"),
                            ("AWS_S3_FILE_RENAME", "AWS S3 File Rename"),
                            ("AWS_S3_FILE_UPLOAD", "AWS S3 File Upload"),
                            ("AWS_S3_GEN_POST_URL", "AWS S3 Generate Post Url"),
                            ("AWS_SQS_QUEUE", "AWS SQS Queue"),
                            ("AWS_CLOUDFRONT_URL", "AWS Cloudfront Url"),
                        ],
                        db_index=True,
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("value", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "system_api",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("CHAT_SERVER_ACTIVE", "Chat Server Active"),
                            ("ALERT_SERVER_ACTIVE", "Alert Server Active"),
                            ("DEFAULT_PROFILE_IMAGE", "Default Profile Image"),
                            ("DEFAULT_BANNER_IMAGE", "Default Banner Image"),
                        ],
                        db_index=True,
                        max_length=128,
                        unique=True,
                    ),
                ),
                ("value", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "system_setting",
            },
        ),
        migrations.CreateModel(
            name="ApiEndpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "app",
                    models.CharField(
                        choices=[
                            ("DIVESITE", "Dive Site"),
                            ("HOME", "Home"),
                            ("LOGBOOK", "Logbook"),
                            ("USER", "User"),
                        ],
                        db_index=True,
                        max_length=128,
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("url", models.CharField(max_length=128)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "api_endpoint",
                "unique_together": {("app", "key")},
            },
        ),
    ]
