# Generated by Django 4.0.5 on 2022-11-03 22:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiveLogApi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('value', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'divelog_api',
            },
        ),
        migrations.CreateModel(
            name='SettingsApi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('value', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'settings_api',
            },
        ),
        migrations.CreateModel(
            name='SystemApi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('ALERTING_ALERTS', 'Alerting Alerts'), ('ALERTING_BUDDY_REQUEST', 'Alerting Buddy Request'), ('ALERTING_NOTIFY_STAFF', 'Alerting Notify Staff'), ('ALERTING_SERVER', 'Alerting Server'), ('SETTINGS_SERVER', 'Settings Server'), ('CHAT_SERVER', 'Chat Server'), ('DIVE_SERVER', 'Dive Server'), ('API_SERVER', 'API Server'), ('AWS_S3_BUCKET', 'AWS S3 Bucket'), ('AWS_S3_FILE_DELETE', 'AWS S3 File Delete'), ('AWS_S3_FILE_HEADERS', 'AWS S3 File Headers'), ('AWS_S3_FILE_RENAME', 'AWS S3 File Rename'), ('AWS_S3_FILE_UPLOAD', 'AWS S3 File Upload'), ('AWS_S3_GEN_POST_URL', 'AWS S3 Generate Post Url'), ('AWS_SQS_QUEUE', 'AWS SQS Queue'), ('AWS_CLOUDFRONT_URL', 'AWS Cloudfront Url'), ('BILLING_PROCESSORS', 'Billing Processors'), ('BILLING_AUTHORIZE_CC', 'Billing Authorize CC')], db_index=True, max_length=128, unique=True)),
                ('value', models.CharField(max_length=128)),
                ('share_with_chat', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'system_api',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('CHAT_SERVER_ACTIVE', 'Chat Server Active')], db_index=True, max_length=128, unique=True)),
                ('value', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'system_setting',
            },
        ),
    ]
