# Generated by Django 4.0.1 on 2022-01-28 04:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preference', models.CharField(choices=[('site_name', 'SITE_NAME'), ('layout', 'SITE_LAYOUT')], max_length=64, unique=True)),
                ('content', models.TextField()),
            ],
            options={
                'db_table': 'preference',
            },
        ),
        migrations.CreateModel(
            name='ProcessorSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('value', models.CharField(max_length=64)),
            ],
            options={
                'db_table': 'processor_setting',
            },
        ),
        migrations.CreateModel(
            name='SystemApi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('ALERTING_URL', 'Alerting Url'), ('ALERTING_NOTIFY_STAFF', 'Alerting Notify Staff'), ('AWS_S3_UPLOAD', 'AWS S3 Upload'), ('AWS_SQS_QUEUE', 'AWS SQS Queue'), ('LAYOUT_DEFAULT_LAYOUT', 'Default Layout'), ('LAYOUT_PAGE_DEFAULT', 'Page Default'), ('BILLING_PROCESSORS', 'Billing Processors'), ('BILLING_AUTHORIZE_CC', 'Billing Authorize CC')], db_index=True, max_length=128)),
                ('url', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'system_api',
                'ordering': ['key'],
            },
        ),
        migrations.CreateModel(
            name='SystemQueue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=128)),
                ('queue', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'system_queue',
            },
        ),
    ]
