# Generated by Django 4.0.5 on 2023-01-11 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemapi',
            name='key',
            field=models.CharField(choices=[('ALERTING_ALERTS', 'Alerting Alerts'), ('ALERTING_BUDDY_REQUEST', 'Alerting Buddy Request'), ('ALERTING_NOTIFY_STAFF', 'Alerting Notify Staff'), ('ALERTING_SERVER', 'Alerting Server'), ('SETTINGS_SERVER', 'Settings Server'), ('CHAT_SERVER', 'Chat Server'), ('DIVE_SERVER', 'Dive Server'), ('SETTINGS_SERVER', 'Settings Server'), ('API_SERVER', 'API Server'), ('AWS_S3_BUCKET', 'AWS S3 Bucket'), ('AWS_S3_FILE_DELETE', 'AWS S3 File Delete'), ('AWS_S3_FILE_HEADERS', 'AWS S3 File Headers'), ('AWS_S3_FILE_RENAME', 'AWS S3 File Rename'), ('AWS_S3_FILE_UPLOAD', 'AWS S3 File Upload'), ('AWS_S3_GEN_POST_URL', 'AWS S3 Generate Post Url'), ('AWS_SQS_QUEUE', 'AWS SQS Queue'), ('AWS_CLOUDFRONT_URL', 'AWS Cloudfront Url'), ('BILLING_PROCESSORS', 'Billing Processors'), ('BILLING_AUTHORIZE_CC', 'Billing Authorize CC')], db_index=True, max_length=128, unique=True),
        ),
    ]
