# Generated by Django 5.0 on 2024-06-07 05:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sitesettings", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Endpoint",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("key", models.CharField(max_length=128)),
                ("url", models.CharField(max_length=128)),
                (
                    "verb",
                    models.CharField(
                        choices=[
                            ("POST", "POST"),
                            ("GET", "GET"),
                            ("PUT", "PUT"),
                            ("DELETE", "DELETE"),
                        ],
                        max_length=128,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "system",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="endpoints",
                        to="sitesettings.systemapi",
                    ),
                ),
            ],
            options={
                "db_table": "endpoint",
                "unique_together": {("system", "key")},
            },
        ),
        migrations.CreateModel(
            name="EndpointParam",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("param", models.CharField(max_length=64)),
                (
                    "endpoint",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="params",
                        to="sitesettings.systemapi",
                    ),
                ),
            ],
            options={
                "db_table": "endpoint_param",
                "unique_together": {("endpoint", "param")},
            },
        ),
        migrations.DeleteModel(
            name="ApiEndpoint",
        ),
    ]
