# Generated by Django 4.1.4 on 2023-01-11 15:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0002_alter_systemapi_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSApi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('value', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'aws_api',
            },
        ),
        migrations.CreateModel(
            name='LogbookApi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('value', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'logbook_api',
            },
        ),
        migrations.AlterField(
            model_name='systemapi',
            name='key',
            field=models.CharField(choices=[('ALERTING_ALERTS', 'Alerting Alerts'), ('ALERTING_BUDDY_REQUEST', 'Alerting Buddy Request'), ('ALERTING_NOTIFY_STAFF', 'Alerting Notify Staff'), ('ALERTING_SERVER', 'Alerting Server'), ('SETTINGS_SERVER', 'Settings Server'), ('AWS_SERVER', 'AWS Server'), ('CHAT_SERVER', 'Chat Server'), ('LOGBOOK_SERVER', 'Logbook Server'), ('SETTINGS_SERVER', 'Settings Server'), ('API_SERVER', 'API Server'), ('AWS_S3_BUCKET', 'AWS S3 Bucket'), ('AWS_S3_FILE_DELETE', 'AWS S3 File Delete'), ('AWS_S3_FILE_HEADERS', 'AWS S3 File Headers'), ('AWS_S3_FILE_RENAME', 'AWS S3 File Rename'), ('AWS_S3_FILE_UPLOAD', 'AWS S3 File Upload'), ('AWS_S3_GEN_POST_URL', 'AWS S3 Generate Post Url'), ('AWS_SQS_QUEUE', 'AWS SQS Queue'), ('AWS_CLOUDFRONT_URL', 'AWS Cloudfront Url'), ('BILLING_PROCESSORS', 'Billing Processors'), ('BILLING_AUTHORIZE_CC', 'Billing Authorize CC')], db_index=True, max_length=128, unique=True),
        ),
    ]
