# Generated by Django 5.0 on 2024-05-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sitesettings", "0002_alter_flagoption_instance_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="systemapi",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
