# Generated by Django 4.1.4 on 2023-01-11 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0003_awsapi_logbookapi_alter_systemapi_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiveLogApi',
        ),
    ]
