# Generated by Django 4.1.4 on 2023-01-12 21:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0006_alertingapi_alter_systemapi_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatApi',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('value', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'chat_api',
            },
        ),
    ]
