# Generated by Django 4.1.5 on 2023-01-20 18:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0007_chatapi'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(choices=[('WEATHER_API', 'Weather API')], db_index=True, max_length=128, unique=True)),
                ('value', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'api_key',
            },
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(choices=[('CHAT_SERVER_ACTIVE', 'Chat Server Active'), ('DEFAULT_PROFILE_IMAGE', 'Default Profile Image')], db_index=True, max_length=128, unique=True),
        ),
    ]
