# Generated by Django 4.0.5 on 2023-02-13 05:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0008_apikey_alter_systemsetting_key'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApiEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('app', models.CharField(choices=[('DIVESITE', 'Dive Site'), ('HOME', 'Home'), ('LOGBOOK', 'Logbook'), ('USER', 'User')], db_index=True, max_length=128, unique=True)),
                ('key', models.CharField(max_length=128)),
                ('url', models.CharField(max_length=128)),
                ('share_with_chat', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'api_endpoint',
                'unique_together': {('app', 'key')},
            },
        ),
    ]
