# Generated by Django 4.0.5 on 2023-02-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0009_apiendpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apiendpoint',
            name='app',
            field=models.CharField(choices=[('DIVESITE', 'Dive Site'), ('HOME', 'Home'), ('LOGBOOK', 'Logbook'), ('USER', 'User')], db_index=True, max_length=128),
        ),
    ]
