# Generated by Django 4.0.5 on 2023-02-13 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0010_alter_apiendpoint_app'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apiendpoint',
            old_name='share_with_chat',
            new_name='is_active',
        ),
    ]
