# Generated by Django 4.1.7 on 2023-04-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0011_rename_share_with_chat_apiendpoint_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemsetting',
            name='key',
            field=models.CharField(choices=[('CHAT_SERVER_ACTIVE', 'Chat Server Active'), ('DEFAULT_PROFILE_IMAGE', 'Default Profile Image'), ('DEFAULT_BANNER_IMAGE', 'Default Banner Image')], db_index=True, max_length=128, unique=True),
        ),
    ]
