# Generated by Django 4.1.7 on 2023-04-18 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0012_alter_systemsetting_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apikey',
            name='key',
            field=models.CharField(choices=[('WEATHER_API', 'Weather API'), ('GOOGLE_MAPS', 'Google Maps')], db_index=True, max_length=128, unique=True),
        ),
    ]
