# Generated by Django 4.1.7 on 2023-05-12 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0013_alter_apikey_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemapi',
            name='share_with_chat',
        ),
    ]
