# Generated by Django 4.2.1 on 2023-05-12 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0014_remove_systemapi_share_with_chat'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertingapi',
            name='verb',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='awsapi',
            name='verb',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billingapi',
            name='verb',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='chatapi',
            name='verb',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='logbookapi',
            name='verb',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settingsapi',
            name='verb',
            field=models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], default='GET', max_length=128),
            preserve_default=False,
        ),
    ]
