# Generated by Django 4.2.5 on 2023-11-04 19:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0015_alertingapi_verb_awsapi_verb_billingapi_verb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(db_index=True, max_length=128, unique=True)),
                ('value', models.CharField(max_length=128)),
                ('verb', models.CharField(choices=[('POST', 'POST'), ('GET', 'GET'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=128)),
                ('flag', models.CharField(max_length=128)),
                ('instance_type', models.PositiveSmallIntegerField(choices=[(0, 'Review'), (1, 'Checkin')])),
            ],
            options={
                'db_table': 'flag_option',
            },
        ),
    ]
