# Generated by Django 4.2.5 on 2023-11-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0018_remove_flagoption_key_remove_flagoption_value_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagoption',
            name='instance_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Checkin'), (0, 'Review')]),
        ),
    ]
