# Generated by Django 4.2.5 on 2023-11-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0019_alter_flagoption_instance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagoption',
            name='instance_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Review'), (1, 'Checkin')]),
        ),
    ]
