# Generated by Django 5.0 on 2023-12-16 18:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0020_alter_flagoption_instance_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='SNSSubscriptionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=40)),
                ('token', models.CharField(max_length=40)),
                ('topic_arn', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=128)),
                ('subscribe_url', models.CharField(max_length=256)),
                ('timestamp', models.DateTimeField()),
                ('signature_version', models.PositiveSmallIntegerField()),
                ('signature', models.CharField(max_length=128)),
                ('signing_cert_url', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'sns_subscription_requests',
            },
        ),
        migrations.AlterField(
            model_name='flagoption',
            name='instance_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Checkin'), (0, 'Review')]),
        ),
    ]
