# Generated by Django 5.0 on 2023-12-16 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0021_snssubscriptionrequest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snssubscriptionrequest',
            name='message_id',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
