# Generated by Django 5.0 on 2023-12-16 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0022_alter_snssubscriptionrequest_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flagoption',
            name='instance_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Review'), (1, 'Checkin')]),
        ),
        migrations.AlterField(
            model_name='snssubscriptionrequest',
            name='signature',
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='snssubscriptionrequest',
            name='signing_cert_url',
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name='snssubscriptionrequest',
            name='subscribe_url',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
