# Generated by Django 5.0 on 2023-12-17 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0023_alter_flagoption_instance_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='snssubscriptionrequest',
            name='is_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='flagoption',
            name='instance_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Checkin'), (0, 'Review')]),
        ),
    ]
