# Generated by Django 5.0 on 2024-02-11 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesettings", "0024_snssubscriptionrequest_is_confirmed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flagoption",
            name="instance_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Review"), (1, "Checkin")]
            ),
        ),
        migrations.AlterField(
            model_name="snssubscriptionrequest",
            name="subscribe_url",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="key",
            field=models.CharField(
                choices=[
                    ("CHAT_SERVER_ACTIVE", "Chat Server Active"),
                    ("ALERT_SERVER_ACTIVE", "Alert Server Active"),
                    ("DEFAULT_PROFILE_IMAGE", "Default Profile Image"),
                    ("DEFAULT_BANNER_IMAGE", "Default Banner Image"),
                ],
                db_index=True,
                max_length=128,
                unique=True,
            ),
        ),
    ]
