# Generated by Django 5.0 on 2024-02-11 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesettings", "0025_alter_flagoption_instance_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flagoption",
            name="instance_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Checkin"), (0, "Review")]
            ),
        ),
        migrations.AlterField(
            model_name="snssubscriptionrequest",
            name="signature",
            field=models.CharField(max_length=512, unique=True),
        ),
    ]
