# Generated by Django 5.0 on 2024-02-11 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesettings", "0026_alter_flagoption_instance_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snssubscriptionrequest",
            name="token",
            field=models.CharField(max_length=512),
        ),
    ]
