# Generated by Django 5.0 on 2024-02-11 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesettings", "0027_alter_snssubscriptionrequest_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flagoption",
            name="instance_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Review"), (1, "Checkin")]
            ),
        ),
        migrations.AlterField(
            model_name="snssubscriptionrequest",
            name="signature",
            field=models.CharField(max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name="snssubscriptionrequest",
            name="signing_cert_url",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="snssubscriptionrequest",
            name="subscribe_url",
            field=models.CharField(max_length=256, unique=True),
        ),
        migrations.AlterField(
            model_name="snssubscriptionrequest",
            name="token",
            field=models.CharField(max_length=40),
        ),
    ]
