# Generated by Django 5.0 on 2024-02-11 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesettings", "0028_alter_snssubscriptionrequest_signature_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flagoption",
            name="instance_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Review"), (1, "Checkin")]
            ),
        ),
        migrations.AlterField(
            model_name="snssubscriptionrequest",
            name="subscribe_url",
            field=models.TextField(),
        ),
    ]
