# Generated by Django 5.0 on 2024-02-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesettings", "0029_alter_flagoption_instance_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="snssubscriptionrequest",
            name="signing_cert_url",
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
