# Generated by Django 5.0 on 2024-02-11 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesettings", "0030_alter_snssubscriptionrequest_signing_cert_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flagoption",
            name="instance_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Checkin"), (0, "Review")]
            ),
        ),
        migrations.AlterField(
            model_name="snssubscriptionrequest",
            name="signing_cert_url",
            field=models.CharField(max_length=256),
        ),
    ]
