# Generated by Django 5.0 on 2024-02-11 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sitesettings", "0031_alter_flagoption_instance_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flagoption",
            name="instance_type",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Review"), (1, "Checkin")]
            ),
        ),
        migrations.AlterField(
            model_name="snssubscriptionrequest",
            name="token",
            field=models.TextField(),
        ),
    ]
