# Generated by Django 6.0.7 on 2026-08-12 18:59

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Logbook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=144)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logbook',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LogbookFolder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logbook_folders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logbook_folder',
                'unique_together': {('user', 'name')},
            },
        ),
        migrations.CreateModel(
            name='LogbookTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'logbook_tag',
                'unique_together': {('user', 'name')},
            },
        ),
    ]
