# Generated by Django 4.1.7 on 2023-04-06 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logbooks', '0002_alter_logbook_id_alter_logbookfolder_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logbooktag',
            name='guid',
        ),
    ]
