# Generated by Django 6.0.7 on 2026-08-12 18:59

import django.db.models.deletion
import django.utils.timezone
import scuba.accounts.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=512)),
                ('profile_image', models.CharField(max_length=128)),
                ('followers_count', models.PositiveSmallIntegerField(default=0)),
                ('buddy_count', models.PositiveSmallIntegerField(default=0)),
                ('reviews_count', models.PositiveSmallIntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'view_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='FlagOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flag', models.CharField(max_length=128)),
                ('instance_type', models.PositiveSmallIntegerField(choices=[(1, 'Checkin'), (0, 'Review')])),
            ],
            options={
                'db_table': 'flag_option',
            },
        ),
        migrations.CreateModel(
            name='UserDivesiteFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notify', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_divesites_favorites',
            },
        ),
        migrations.CreateModel(
            name='UserDivesiteRecentlyViewed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed_date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_divesites_recently_viewed',
            },
        ),
        migrations.CreateModel(
            name='UserEmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name=scuba.accounts.models.User)),
                ('is_primary', models.BooleanField(default=False)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'user email addresses',
                'db_table': 'user_email',
            },
        ),
        migrations.CreateModel(
            name='UserFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_type', models.PositiveSmallIntegerField(choices=[(1, 'Checkin'), (0, 'Review')])),
                ('instance_id', models.UUIDField()),
                ('is_private', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_feed',
            },
        ),
        migrations.CreateModel(
            name='UserFeedFlagged',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'user feed flagged',
                'db_table': 'user_feed_flagged',
            },
        ),
        migrations.CreateModel(
            name='UserFollower',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_following', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'user followers',
                'db_table': 'user_follower',
            },
        ),
        migrations.CreateModel(
            name='UserHidden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_hidden',
            },
        ),
        migrations.CreateModel(
            name='UserIsPremier',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_is_premier',
            },
        ),
        migrations.CreateModel(
            name='UserLocation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('postal_code', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'user_location',
            },
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.CharField(max_length=512)),
                ('iso_country', models.CharField(default='US', max_length=2)),
                ('login_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'user logins',
                'db_table': 'user_login',
                'ordering': ['-login_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfileImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.CharField(max_length=128)),
            ],
            options={
                'db_table': 'user_profile_image',
            },
        ),
        migrations.CreateModel(
            name='UserRecentActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'user_recent_activity',
            },
        ),
        migrations.CreateModel(
            name='UserSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('setting', models.PositiveSmallIntegerField(choices=[(0, 'Display Mode')])),
                ('value', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'user settings',
                'db_table': 'user_setting',
            },
        ),
        migrations.CreateModel(
            name='UserSignupCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iso_country', models.CharField(max_length=5)),
            ],
            options={
                'verbose_name_plural': 'user signup country',
                'db_table': 'user_signup_country',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('username', models.CharField(db_index=True, max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('is_admin', models.BooleanField(default=False)),
                ('aws_id', models.CharField(blank=True, max_length=10)),
                ('date_of_birth', models.DateField(default='1970-04-01')),
                ('can_add_divesites', models.BooleanField(default=False)),
                ('reputation', models.PositiveSmallIntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
                ('confirmed', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('last_login_date', models.DateTimeField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'db_table': 'user',
                'ordering': ['-date_joined'],
            },
        ),
        migrations.CreateModel(
            name='UserBlocked',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('blocked_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('buddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_buddy', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'blocked users',
                'db_table': 'user_blocked',
            },
        ),
        migrations.CreateModel(
            name='UserBuddy',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hide', models.BooleanField(default=False)),
                ('is_following', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('buddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user buddies',
                'db_table': 'user_buddy',
            },
        ),
        migrations.CreateModel(
            name='UserBuddyRemove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('removed_date', models.DateTimeField(auto_now_add=True)),
                ('buddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user buddies removed',
                'db_table': 'user_buddy_removed',
            },
        ),
        migrations.CreateModel(
            name='UserBuddyRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('buddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_requested', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_buddy_request',
            },
        ),
        migrations.CreateModel(
            name='UserCollection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('is_public', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_collection',
            },
        ),
        migrations.CreateModel(
            name='UserCollectionItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_type', models.PositiveSmallIntegerField(choices=[(1, 'Dive Shop'), (0, 'Divesite')])),
                ('instance_id', models.UUIDField()),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.usercollection')),
            ],
            options={
                'db_table': 'user_collection_item',
            },
        ),
        migrations.CreateModel(
            name='UserConfirmationCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.PositiveIntegerField()),
                ('redeemed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmation_codes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_confirmation_code',
            },
        ),
        migrations.CreateModel(
            name='UserDiveSiteBuddyFinder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('divesite_id', models.CharField(max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddyfinder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_divesite_buddy_finder',
            },
        ),
    ]
