# Generated by Django 4.1.4 on 2022-12-26 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersetting',
            name='setting',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Display Mode')]),
        ),
    ]
