# Generated by Django 5.0 on 2024-02-12 00:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("divesites", "0001_initial"),
        ("sitesettings", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userdivesitefavorite",
            name="divesite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="divesites.divesite"
            ),
        ),
        migrations.AddField(
            model_name="userdivesitefavorite",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="divesites_favorites",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userdivesiterecentlyviewed",
            name="divesite",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="divesites.divesite"
            ),
        ),
        migrations.AddField(
            model_name="userdivesiterecentlyviewed",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="divesites_recently_viewed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="useremail",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="emails",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userfeed",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userfeedflagged",
            name="flag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="sitesettings.flagoption",
            ),
        ),
        migrations.AddField(
            model_name="userfeedflagged",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userfeedflagged",
            name="user_feed",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flags",
                to="accounts.userfeed",
            ),
        ),
        migrations.AddField(
            model_name="userfollower",
            name="follower",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userfollower",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userhidden",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userispremier",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userlocation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="locations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userlogin",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="logins",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="userprofileimage",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userrecentactivity",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="activities",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usersetting",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="usersignupcountry",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="userblocked",
            unique_together={("user", "buddy")},
        ),
        migrations.AlterUniqueTogether(
            name="userbuddy",
            unique_together={("user", "buddy")},
        ),
        migrations.AlterUniqueTogether(
            name="userbuddyrequest",
            unique_together={("user", "buddy")},
        ),
        migrations.AlterUniqueTogether(
            name="usercollectionitem",
            unique_together={("instance_id", "instance_type", "collection")},
        ),
        migrations.AlterUniqueTogether(
            name="userdivesitebuddyfinder",
            unique_together={("user", "divesite_id")},
        ),
        migrations.AlterUniqueTogether(
            name="userdivesitefavorite",
            unique_together={("user", "divesite")},
        ),
        migrations.AlterUniqueTogether(
            name="userfeed",
            unique_together={("instance_id", "instance_type", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="userfeedflagged",
            unique_together={("user_feed", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="userfollower",
            unique_together={("user", "follower")},
        ),
    ]
