# Generated by Django 4.2.4 on 2023-09-18 14:26

from django.db import migrations

class Migration(migrations.Migration):
    sql = """
    CREATE VIEW view_profile as
    select u.id, u.username, u.first_name, u.last_name, up.image as profile_image, u.is_private,
    u.is_active,
    (select count(*) from user_follower uf where uf.user_id = u.id) as followers_count,
    (select count(*) from user_buddy ub where ub.user_id = u.id) as buddy_count,
    (select count(*) from divesite_review dr where dr.user_id = u.id) as reviews_count,
    (select ul.city from user_location ul where ul.user_id = u.id and ul.is_active=1) as location
    from user u
    left outer join user_location ul on ul.user_id = u.id
    left outer join user_profile_image up on up.user_id = u.id;
    """
    dependencies = [
        ('accounts', '0002_initial'),
    ]
    operations = [
        migrations.RunSQL(sql)
    ]
