# Generated by Django 4.0.5 on 2023-02-14 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userconfirmationcode'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userconfirmationcode',
            old_name='confirmation_code',
            new_name='code',
        ),
    ]
