# Generated by Django 4.1.5 on 2023-03-02 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_confirmation_code_userconfirmationcode_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='setup_complete',
            field=models.BooleanField(default=False),
        ),
    ]
