# Generated by Django 4.1.5 on 2023-03-16 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_date_of_birth_user_setup_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(default='1970-01-01'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='UserLogin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('device', models.CharField(max_length=512)),
                ('iso_country', models.CharField(default='US', max_length=2)),
                ('login_date', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_logins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user logins',
                'db_table': 'user_login',
                'ordering': ['-login_date'],
            },
        ),
    ]
