# Generated by Django 4.1.5 on 2023-03-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_remove_user_is_active_remove_user_is_staff_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='aws_id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='guid',
        ),
        migrations.RemoveField(
            model_name='account',
            name='is_blocked',
        ),
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
