# Generated by Django 4.1.5 on 2023-03-25 08:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_account_aws_id_remove_account_guid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='setup_complete',
            new_name='confirmed',
        ),
    ]
