# Generated by Django 4.1.5 on 2023-03-29 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_rename_setup_complete_user_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userconfirmationcode',
            name='code',
            field=models.PositiveIntegerField(),
        ),
    ]
