# Generated by Django 4.1.5 on 2023-03-30 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0001_initial'),
        ('accounts', '0013_userconfirmationcode_redeemed_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFavoriteDivesite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notify', models.BooleanField(default=True)),
                ('divesite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divesites.divesite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite_divesites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_favorite_divesites',
            },
        ),
    ]
