# Generated by Django 4.1.5 on 2023-03-31 00:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0003_divesitebanner'),
        ('accounts', '0014_userfavoritedivesite'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDivesiteFavorite',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notify', models.BooleanField(default=True)),
                ('divesite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divesites.divesite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divesites_favorites', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_divesites_favorites',
            },
        ),
        migrations.CreateModel(
            name='UserDivesiteRecentlyViewed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('viewed', models.DateTimeField(auto_now=True)),
                ('divesite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divesites.divesite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='divesites_recently_viewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_divesites_recently_viewed',
            },
        ),
        migrations.DeleteModel(
            name='UserFavoriteDivesite',
        ),
    ]
