# Generated by Django 4.1.7 on 2023-03-31 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_userrecentactivity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrecentactivity',
            old_name='viewed',
            new_name='activity_date',
        ),
    ]
