# Generated by Django 4.1.7 on 2023-04-01 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_rename_viewed_userrecentactivity_activity_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdivesiterecentlyviewed',
            old_name='viewed',
            new_name='viewed_date',
        ),
    ]
