# Generated by Django 4.1.7 on 2023-04-03 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0007_alter_divesite_lat_alter_divesite_long'),
        ('accounts', '0018_rename_viewed_userdivesiterecentlyviewed_viewed_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='apikey',
        ),
        migrations.AlterUniqueTogether(
            name='userdivesitefavorite',
            unique_together={('user', 'divesite')},
        ),
    ]
