# Generated by Django 4.1.7 on 2023-04-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_account_apikey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuddyrequest',
            name='is_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
