# Generated by Django 4.1.7 on 2023-04-03 22:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_userbuddyrequest_is_accepted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbuddyrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buddy_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
