# Generated by Django 4.1.7 on 2023-04-03 23:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_userbuddyrequest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserBuddyRemove',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('removed_date', models.DateTimeField(auto_now_add=True)),
                ('buddy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'user buddies removed',
                'db_table': 'user_buddy_removed',
            },
        ),
    ]
