# Generated by Django 4.1.7 on 2023-04-13 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_userbuddyremove'),
    ]

    operations = [
        migrations.AddField(
            model_name='userbuddy',
            name='follow',
            field=models.BooleanField(default=True),
        ),
    ]
