# Generated by Django 4.1.7 on 2023-04-13 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_userbuddy_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userbuddy',
            old_name='follow',
            new_name='is_following',
        ),
    ]
