# Generated by Django 4.1.7 on 2023-04-26 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_rename_follow_userbuddy_is_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userblocked',
            name='buddy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocked_buddy', to=settings.AUTH_USER_MODEL),
        ),
    ]
