# Generated by Django 4.1.7 on 2023-04-27 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_alter_user_date_of_birth'),
        ('accounts', '0025_alter_userblocked_buddy'),
    ]

    operations = [
    ]
