# Generated by Django 4.1.7 on 2023-04-28 00:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_merge_20230427_2139'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserIsPrime',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_is_prime',
            },
        ),
    ]
