# Generated by Django 4.1.7 on 2023-04-28 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_userisprime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserIsPrime',
            new_name='UserIsPremier',
        ),
        migrations.AlterModelTable(
            name='userispremier',
            table='user_is_premier',
        ),
    ]
