# Generated by Django 4.2.4 on 2023-09-11 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_rename_userisprime_userispremier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default='x', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
