# Generated by Django 4.2.4 on 2023-09-11 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_rename_userisprime_userispremier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
