# Generated by Django 4.2.5 on 2023-09-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default='x', max_length=40, unique=True),
            preserve_default=False,
        ),
    ]
