# Generated by Django 4.2.5 on 2023-09-16 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_userfollower'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlocation',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
