# Generated by Django 4.2.5 on 2023-10-03 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20230918_1426'),
    ]

    operations = [
        migrations.CreateModel(
            name='ViewProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('username', models.CharField(db_index=True, max_length=40, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('location', models.CharField(max_length=512)),
                ('profile_image', models.CharField(max_length=128)),
                ('followers_count', models.PositiveSmallIntegerField(default=0)),
                ('buddy_count', models.PositiveSmallIntegerField(default=0)),
                ('reviews_count', models.PositiveSmallIntegerField(default=0)),
                ('is_private', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'view_profile',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserFeed',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_type', models.PositiveSmallIntegerField(choices=[(0, 'Review')])),
                ('instance_id', models.UUIDField()),
                ('is_private', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_feed',
            },
        ),
    ]
