# Generated by Django 4.2.5 on 2023-10-05 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_viewprofile_userfeed'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='userfeed',
            unique_together={('instance_id', 'instance_type', 'user')},
        ),
    ]
