# Generated by Django 4.2.5 on 2023-10-11 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_usercollection_usercollectionitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollectionitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item', to='accounts.usercollection'),
        ),
    ]
