# Generated by Django 4.2.5 on 2023-10-23 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_alter_usercollectionitem_collection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollectionitem',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.usercollection'),
        ),
        migrations.AlterField(
            model_name='usercollectionitem',
            name='instance_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Divesite'), (1, 'Dive Shop')]),
        ),
    ]
