# Generated by Django 4.2.5 on 2023-10-31 16:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_alter_usercollectionitem_collection_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollectionitem',
            name='instance_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dive Shop'), (0, 'Divesite')]),
        ),
        migrations.AlterField(
            model_name='userfeed',
            name='instance_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Checkin'), (0, 'Review')]),
        ),
        migrations.CreateModel(
            name='UserFlagged',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('instance_type', models.PositiveSmallIntegerField(choices=[(1, 'Checkin'), (0, 'Review')])),
                ('instance_id', models.UUIDField()),
                ('is_private', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_flagged',
                'unique_together': {('instance_id', 'instance_type', 'user')},
            },
        ),
    ]
