# Generated by Django 4.2.5 on 2023-11-02 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_usercollectionitem_instance_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userflagged',
            name='is_private',
        ),
        migrations.AddField(
            model_name='userflagged',
            name='is_flagged',
            field=models.BooleanField(default=True),
        ),
    ]
