# Generated by Django 4.2.5 on 2023-11-02 19:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_remove_userflagged_is_private_userflagged_is_flagged'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFeedFlagged',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_flagged', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_feed_flagged',
            },
        ),
        migrations.AlterField(
            model_name='usercollectionitem',
            name='instance_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Divesite'), (1, 'Dive Shop')]),
        ),
        migrations.AlterField(
            model_name='userfeed',
            name='instance_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Review'), (1, 'Checkin')]),
        ),
        migrations.DeleteModel(
            name='UserFlagged',
        ),
        migrations.AddField(
            model_name='userfeedflagged',
            name='user_feed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='accounts.userfeed'),
        ),
        migrations.AlterUniqueTogether(
            name='userfeedflagged',
            unique_together={('user_feed', 'user')},
        ),
    ]
