# Generated by Django 4.2.5 on 2023-11-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0042_userfeedflagged_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userfeedflagged',
            name='reason',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userfeedflagged',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
    ]
