# Generated by Django 4.2.5 on 2023-11-04 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_userfeedflagged_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userfeed',
            name='instance_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Checkin'), (0, 'Review')]),
        ),
    ]
