# Generated by Django 4.2.5 on 2023-11-04 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_alter_userfeed_instance_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userfeedflagged',
            options={'verbose_name_plural': 'user feed flagged'},
        ),
        migrations.AlterField(
            model_name='usercollectionitem',
            name='instance_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Dive Shop'), (0, 'Divesite')]),
        ),
        migrations.AlterField(
            model_name='userfeed',
            name='instance_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Review'), (1, 'Checkin')]),
        ),
    ]
