# Generated by Django 4.2.5 on 2023-11-04 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sitesettings', '0020_alter_flagoption_instance_type'),
        ('accounts', '0045_alter_userfeedflagged_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userfeedflagged',
            name='is_flagged',
        ),
        migrations.AddField(
            model_name='userfeedflagged',
            name='flag',
            field=models.ForeignKey(default='6a83a11a-8804-4913-b229-e8f9878ae62c', on_delete=django.db.models.deletion.CASCADE, to='sitesettings.flagoption'),
            preserve_default=False,
        ),
    ]
