# Generated by Django 4.2.5 on 2023-11-09 02:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_alter_userfeed_instance_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHidden',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_hidden',
            },
        ),
    ]
