# Generated by Django 5.0 on 2023-12-16 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_userhidden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Account',
        ),
    ]
