# Generated by Django 5.0 on 2024-01-15 20:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_delete_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercollectionitem',
            name='instance_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Divesite'), (1, 'Dive Shop')]),
        ),
        migrations.AlterField(
            model_name='userfeed',
            name='instance_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Review'), (1, 'Checkin')]),
        ),
        migrations.CreateModel(
            name='UserSignupCountry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('iso_country', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_signup_country',
            },
        ),
    ]
