# Generated by Django 5.0 on 2024-02-11 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0050_alter_usercollectionitem_instance_type_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="usersignupcountry",
            options={"verbose_name_plural": "user signup country"},
        ),
        migrations.AlterField(
            model_name="usercollectionitem",
            name="instance_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Dive Shop"), (0, "Divesite")]
            ),
        ),
    ]
