"""
Django settings for scuba project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

import django.conf.global_settings as DEFAULT_SETTINGS


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
PROJECT_DIR = f"{BASE_DIR}/scuba"
STATIC_ROOT = os.path.join(BASE_DIR, './static')
LOG_DIRECTORY = '/tmp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = int(os.environ.get("DEBUG", default=True))

TEMPLATE_ROOT = ''
if DEBUG:
    TEMPLATE_ROOT = os.path.join(f"{BASE_DIR}/templates")


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2f=t9#vtv*_lwn-%)x@a8q==3c4j-@*es^(gfk1afab^5i*(kr'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'test_pep8',
    'compressor',
    'crispy_forms',
    'crispy_bootstrap5',
    'rest_framework',
    'rest_framework.authtoken',
    'gallery',
    'common',
    'divesites',
    'equipment',
    'entities',
    'logbook',
    'diveshops',
    'utils',
    'api',
    'scuba.accounts',
    'scuba.environ',
    'scuba.friends',
    'scuba.home',
    'scuba.sitesettings',
    # 'django.contrib.admindocs',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'scuba.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_ROOT],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'utils.context_processors.sm',
            ],
        },
    },
]

#AUTHENTICATION_BACKENDS = DEFAULT_SETTINGS.AUTHENTICATION_BACKENDS + \
AUTHENTICATION_BACKENDS = [
    'rest_framework.authentication.TokenAuthentication',
    'utils.middleware.authentication.DefaultBackend',
]

WSGI_APPLICATION = 'scuba.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": os.environ.get("SQL_ENGINE", "django.db.backends.sqlite3"),
        "NAME": os.environ.get("SQL_DATABASE", f"{BASE_DIR}/db.sqlite3"),
        "USER": os.environ.get("SQL_USER", "user"),
        "PASSWORD": os.environ.get("SQL_PASSWORD", "password"),
        "HOST": os.environ.get("SQL_HOST", "localhost"),
        "PORT": os.environ.get("SQL_PORT", "3306"),
    }
}

#AUTH_USER_MODEL = 'accounts.User'


REST_FRAMEWORK = {
    'PAGINATE_BY': 2,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'NON_FIELD_ERRORS_KEY': 'errors',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}


# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_REDIRECT_URL = '/home'
LOGIN_URL = '/login'


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_FINDERS = DEFAULT_SETTINGS.STATICFILES_FINDERS + [
    'compressor.finders.CompressorFinder',
    'yarn.finders.YarnFinder',]

YARN_ROOT_PATH = BASE_DIR



# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SERVER_EMAIL = 'no-reply@scubamob.com'


MONGO = {
    'USE_REPLICASET': False,
    'HOSTS': [],
    'REPLICASET': {},
    'HOST': 'localhost',
    'PORT': 27017,
    'DATABASE': 'scubamob'
}

NOSQL = 'mongo'


PRODUCTION_MEDIA_URL = '//d1fqxyumeztd89.cloudfront.net/media/'
PRODUCTION_GALLERY_URL = '//s3-us-west-1.amazonaws.com/scubamob.gallery.dev/'


WEATHER_UNDERGROUND = 'weather_underground'
FACEBOOK = 'facebook'
GOOGLE_MAPS = 'google_maps'
GOOGLE_ADDRESS = 'google_address'

FACEBOOK_APP = ''
FACEBOOK_APP_ID = ''
FACEBOOK_API_SECRET = ''

EXTERNAL_INTERFACES = {
    WEATHER_UNDERGROUND: {
        'url': 'http://api.wunderground.com/api/%s/conditions/astronomy/rawtide/q/%s/%s.json',
        'url_latlng': 'http://api.wunderground.com/api/%s/geolookup/conditions/astronomy/rawtide/q/%s,%s.json',
        'method': 'http://api.wunderground.com/api/%s/conditions/q/%s/%s.json',
        'apikey': 'd41784195576cec0',
    },

    FACEBOOK: {
        'app': '178799865530799',
        'secret': '502a5c37f483495170f0559afa4ad1ca',
        'url': 'https://graph.facebook.com/oauth/authorize'
    },

    GOOGLE_ADDRESS: {
        'url': 'http://maps.googleapis.com/maps/api/geocode/json?address=%s&sensor=false'
    }
}

MEMCACHE = {
    'server': ['127.0.0.1:11211']
}

# set up the external API stuff
WEATHER_API_KEY = 'd41784195576cec0' + '-'
WEATHER_API_URL = 'http://api.wunderground.com/api/%s/conditions/q/%s/%s.json'
#WEATHER_API_LAT_LNG_URL = 'http://api.wunderground.com/api/%s/conditions/q/%s/%s,%s.json'
WEATHER_API_LAT_LNG_URL = 'http://api.wunderground.com/api/%s/geolookup/conditions/astronomy/rawtide/q/%s,%s.json'

NOSQL_HOST = 'localhost'
NOSQL_PASSWORD = 'notset'
NOSQL_PORT = 27017
NOSQL_DB = 'scubamob'

#AWS_ACCESS_KEY_ID = 'AKIAJAKVVBLJNXEABZVQ'
#AWS_SECRET_ACCESS_KEY = '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'
AWS_ACCESS_KEY_ID = 'AKIAJDVN6XIBZ5I7TVSA'
AWS_SECRET_ACCESS_KEY = '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'

# Here is the bucket file pattern.  It goes in the following manner:
# account guid / album id / file name
GALLERY_BUCKET = 'scubamob.gallery.dev'

EMAIL_BACKEND = 'django_ses.SESBackend'
DEFAULT_FROM_EMAIL = 'no-reply@scubamob.com'
GOOGLE_API_KEY = 'AIzaSyD8CDOojSGLURvXDISrXKHZss1BkOA-Lss'

# this is a constant to be used to compute geodistance stuff
EARTH_RADIUS = 3159

# the following settings are for the mobile apps
MOBILE_HEADER_APP = 'scubaapp'
MOBILE_HEADER_DEVICES = {'smandroid': 'am', 'smios': 'io'}

# maxmind settings
#MAXMIND_URL = 'https://geoip.maxmind.com/geoip/v2.0/city_isp_org/%s'
MAXMIND_URL = 'https://geoip.maxmind.com/geoip/v2.0/city/%s'
MAXMIND_LICENSE = 'hVeqTCTxxU5H'
MAXMIND_USER = '75205'

# define the mongo collections
MONGO_DIVELOGS		= 'divelogs'

DEBUG_IP = '68.101.214.253'

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

TEST_PEP8_DIRS = [PROJECT_DIR]
