"""
Django settings for scuba project.

Generated by 'django-admin startproject' using Django 4.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import os
from pathlib import Path

import django.conf.global_settings as DEFAULT_SETTINGS


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
BASE_URL = 'scubamob.com'
SITE_URL = 'scubamob.com'
TEMPLATE_ROOT = os.path.join(BASE_DIR, './templates')
PROJECT_DIR = os.path.join(BASE_DIR, './scuba')
STATIC_ROOT = os.path.join(BASE_DIR, './static')
LOG_DIRECTORY = '/tmp'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-2f=t9#vtv*_lwn-%)x@a8q==3c4j-@*es^(gfk1afab^5i*(kr'

# ALLOWED_HOSTS = []
ALLOWED_HOSTS = ['localhost:8002', 'localhost']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'django_extensions',
    'corsheaders',
    'compressor',
    'crispy_forms',
    'crispy_bootstrap5',
    'django_bootstrap5',
    'rest_framework',
    'rest_framework.authtoken',
    'scuba.accounts',
    'scuba.aws',
    'scuba.cache',
    'scuba.content',
    'scuba.divegroups',
    'scuba.diveshops',
    'scuba.divesites',
    'scuba.entities',
    'scuba.environ',
    'scuba.equipment',
    'scuba.galleries',
    'scuba.home',
    'scuba.logbooks',
    'scuba.maps',
    'scuba.robots',
    'scuba.search',
    'scuba.security',
    'scuba.sitesettings',
    'scuba.system',
    'django.contrib.admindocs',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'scuba.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [TEMPLATE_ROOT],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'scuba.libs.context_processors.scuba.Scuba',
            ],
        },
    },
]

AUTHENTICATION_BACKENDS = DEFAULT_SETTINGS.AUTHENTICATION_BACKENDS + [
    'rest_framework.authentication.TokenAuthentication',
    'scuba.libs.authentication.adminoverride.AdminOverride',
    'scuba.libs.authentication.usernameauthentication.UsernameAuthentication',
]

WSGI_APPLICATION = 'scuba.wsgi.application'

AUTH_USER_MODEL = 'accounts.User'

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    "default": {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

AUTH_USER_MODEL = 'accounts.User'


REST_FRAMEWORK = {
    'PAGINATE_BY': 2,
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.BasicAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework.authentication.TokenAuthentication',
    ],
    'NON_FIELD_ERRORS_KEY': 'errors',
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ]
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LOGIN_REDIRECT_URL = '/home'
LOGIN_URL = '/login'


# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

USE_I18N = True

USE_TZ = False
TIME_ZONE = 'UTC'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_FINDERS = DEFAULT_SETTINGS.STATICFILES_FINDERS + [
    'compressor.finders.CompressorFinder',
    'yarn.finders.YarnFinder']

YARN_ROOT_PATH = BASE_DIR

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

EMAIL_FROM = 'no-reply@scubamob.com'
EMAIL_BCC = 'no-reply@scubamob.com'

PRODUCTION_GALLERY_URL = '//s3-us-west-1.amazonaws.com/scubamob.gallery.dev/'

FACEBOOK = 'facebook'
GOOGLE_MAPS = 'google_maps'
GOOGLE_ADDRESS = 'google_address'

FACEBOOK_APP = ''
FACEBOOK_APP_ID = ''
FACEBOOK_API_SECRET = ''

# Here is the bucket file pattern.  It goes in the following manner:
# account guid / album id / file name
GALLERY_BUCKET = 'scubamob.gallery.dev'

EMAIL_BACKEND = 'django_ses.SESBackend'
DEFAULT_FROM_EMAIL = 'no-reply@scubamob.com'
GOOGLE_API_KEY = 'AIzaSyD8CDOojSGLURvXDISrXKHZss1BkOA-Lss'

# maxmind settings
MAXMIND_URL = 'https://geoip.maxmind.com/geoip/v2.0/city/%s'
MAXMIND_LICENSE = 'hVeqTCTxxU5H'
MAXMIND_USER = '75205'
MAXMIND_CITY_DB = f"{BASE_DIR}/GeoLite2-City.mmdb"
MAXMIND_USE_DB = True

CRISPY_ALLOWED_TEMPLATE_PACKS = "bootstrap5"
CRISPY_TEMPLATE_PACK = "bootstrap5"

TEST_PEP8_DIRS = [PROJECT_DIR]

# start AWS stuff
PROFILE_BLANK_URL = 'images/profiles/profile-blank.png'
BANNER_BLANK_URL = 'images/divesite-blank.png'
AWS_S3_BUCKET = os.environ.get("AWS_S3_BUCKET", "scubamob-dev")
AWS_S3_BUCKET_PRIVATE = os.environ.get("AWS_S3_BUCKET_PRIVATE", "scubamob-private")
AWS_S3_BUCKET_PRIVATE_REGION = 'us-east-1'
AWS_PROFILE = 'default'
AWS_EMAIL_STORAGE_ROOT = 'emailsent/skmradio'
AWS_CLOUDFRONT = os.environ.get('AWS_CLOUDFRONT', 'https://d2pw8lka09f5g5.cloudfront.net/')
AWS_CLOUDFRONT_DEPLOY = os.environ.get('AWS_CLOUDFRONT_DEPLOY',
                                       'https://d2y2c3a6qt52o9.cloudfront.net/')

FILE_UPLOAD_HANDLERS = ['django.core.files.uploadhandler.TemporaryFileUploadHandler']

SOCKET_SERVER = 'location:3001'
SOCKET_SERVER_ACTIVE = False

# Social Media
SOCIAL_MEDIA = {
    'FACEBOOK': 'https://www.facebook.com/scubamob/',
    'INSTAGRAM': 'https://www.instagram.com/scubamob/',
    'TWITTER': 'https://www.instagram.com/scubamob/'
}

SITE_ID = 1
SITE_NAME = 'Scuba Mob'

VIDEO_TYPES = ['mp4']
IMAGE_TYPES = ['png', 'jpg', 'gif', 'jpeg']
VALID_CONTENT_TYPES = ['image/png', 'image/jpg', 'image/jpeg', 'video/mp4']

COMPRESS_OFFLINE = True
COMPRESS_CSS_HASHING_METHOD = 'content'
COMPRESS_CSS_FILTERS = [
    'compressor.filters.css_default.CssAbsoluteFilter',
    'compressor.filters.cssmin.CSSMinFilter',
]

xCOMPRESS_FILTERS = {
    'css': ['compressor.filters.css_default.CssAbsoluteFilter',
            'compressor.filters.yuglify.YUglifyCSSFilter'],
    'js': ['compressor.filters.jsmin.JSMinFilter',
           'compressor.filters.yuglify.YUglifyJSFilter'],
}

xCOMPRESS_YUGLIFY_BINARY = f"{BASE_DIR}/node_modules/yuglify/bin/yuglify"

CORS_ORIGIN_ALLOW_ALL = True
CORS_ALLOW_ALL_ORIGINS = True

SITE_TITLE = 'ScubaMob'
TITLE_HTML = 'ScubaMob&reg;'
IS_PRODUCTION = False


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'settings': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}

try:
    import sys
    print("settings path", os.environ.get('SETTINGS_PATH', '/scuba'))
    print("settings path", os.environ.get('SETTINGS_PATH', '/scuba'))
    print("settings path", os.environ.get('SETTINGS_PATH', '/scuba'))
    print("settings path", os.environ.get('SETTINGS_PATH', '/scuba'))
    sys.path.append(os.environ.get('SETTINGS_PATH', '/scuba'))
    from system.settings import *   # noqa: F401,F403
except ImportError as exp:
    print('system.settings was not loaded. Continuing with standard settings.\n%s' % exp)
