# Generated by Django 6.0.7 on 2026-08-12 18:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CodeBuildProject',
            fields=[
                ('id', models.CharField(editable=False, max_length=128, primary_key=True, serialize=False)),
                ('project', models.CharField(max_length=128)),
                ('last_successful_build', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'codebuild_project',
            },
        ),
        migrations.CreateModel(
            name='CodePipelineRun',
            fields=[
                ('id', models.CharField(editable=False, max_length=128, primary_key=True, serialize=False)),
                ('pipeline', models.CharField(max_length=128)),
                ('topic_arn', models.CharField(max_length=256)),
                ('run_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'codepipeline_project_run',
            },
        ),
        migrations.CreateModel(
            name='SNSSubscriptionRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(max_length=40, unique=True)),
                ('token', models.TextField()),
                ('topic_arn', models.CharField(max_length=64)),
                ('message', models.CharField(max_length=128)),
                ('subscribe_url', models.TextField()),
                ('timestamp', models.DateTimeField()),
                ('signature_version', models.PositiveSmallIntegerField()),
                ('signature', models.TextField()),
                ('signing_cert_url', models.CharField(max_length=256)),
                ('is_confirmed', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'sns_subscription_requests',
            },
        ),
        migrations.CreateModel(
            name='CodeBuildJob',
            fields=[
                ('id', models.CharField(editable=False, max_length=128, primary_key=True, serialize=False)),
                ('build_status', models.PositiveSmallIntegerField(choices=[(3, 'STOPPED'), (2, 'FAILED'), (1, 'SUCCEEDED'), (0, 'IN_PROGRESS')], default=0)),
                ('logs', models.CharField(max_length=256)),
                ('branch', models.CharField(max_length=256)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='aws.codebuildproject')),
            ],
            options={
                'db_table': 'codebuild_job',
                'ordering': ('-start_time',),
                'get_latest_by': '-start_time',
            },
        ),
        migrations.CreateModel(
            name='CodePipelineState',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notification_rule_arn', models.CharField(max_length=128)),
                ('state', models.CharField(max_length=64)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('pipeline_execution_attempt', models.PositiveSmallIntegerField(default=0)),
                ('payload', models.CharField(max_length=1024)),
                ('pipeline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='states', to='aws.codepipelinerun')),
            ],
            options={
                'db_table': 'codepipeline_state',
            },
        ),
    ]
