# Generated by Django 5.0.6 on 2024-06-05 20:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodeBuildProject",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project", models.CharField(max_length=128)),
                ("last_successful_build", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "codebuild_project",
            },
        ),
        migrations.CreateModel(
            name="CodePipelineRun",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pipeline", models.CharField(max_length=128)),
                ("topic_arn", models.CharField(max_length=256)),
                ("run_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "codepipeline_project_run",
            },
        ),
        migrations.CreateModel(
            name="CodeBuildJob",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "build_status",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (1, "SUCCEEDED"),
                            (0, "IN_PROGRESS"),
                            (2, "FAILED"),
                            (3, "STOPPED"),
                        ],
                        default=0,
                    ),
                ),
                ("logs", models.CharField(max_length=256)),
                ("branch", models.CharField(max_length=256)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jobs",
                        to="aws.codebuildproject",
                    ),
                ),
            ],
            options={
                "db_table": "codebuild_job",
                "ordering": ("-start_time",),
                "get_latest_by": "-start_time",
            },
        ),
        migrations.CreateModel(
            name="CodePipelineState",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notification_rule_arn", models.CharField(max_length=128)),
                ("state", models.CharField(max_length=64)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                (
                    "pipeline_execution_attempt",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("payload", models.CharField(max_length=1024)),
                (
                    "pipeline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="aws.codepipelinerun",
                    ),
                ),
            ],
            options={
                "db_table": "codepipeline_state",
            },
        ),
    ]
