# Generated by Django 4.1.5 on 2023-03-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='template_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Welcome Free Account'), (1, 'Welcome Premium Account'), (2, 'Confirmation Code')], unique=True),
        ),
    ]
