# Generated by Django 4.2.5 on 2023-10-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_article_user'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['url'], name='article_url_9ad36c_idx'),
        ),
    ]
