# Generated by Django 4.2.5 on 2023-11-09 20:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_alter_faqentry_id_alter_faqsection_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('version', models.PositiveSmallIntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('published_date', models.DateField(editable=False, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.article')),
            ],
            options={
                'db_table': 'article_version',
            },
        ),
    ]
