# Generated by Django 5.0 on 2024-02-12 00:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CertificationOrganizationType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("definition", models.CharField(max_length=30)),
            ],
            options={
                "db_table": "certification_organization_type",
            },
        ),
        migrations.CreateModel(
            name="CertificationOrganization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("abbreviation", models.CharField(max_length=10)),
                ("name", models.CharField(max_length=100)),
                ("url", models.URLField(max_length=255)),
                (
                    "certification_organtization_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="entities.certificationorganizationtype",
                    ),
                ),
            ],
            options={
                "db_table": "certification_organization",
            },
        ),
    ]
