# Generated by Django 4.0.5 on 2022-11-03 22:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jumbotron',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('filename', models.CharField(max_length=128)),
                ('jumbotron_type', models.PositiveSmallIntegerField(choices=[(0, 'Video'), (1, 'Image')])),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'home_jumbotron',
            },
        ),
    ]
