# Generated by Django 5.0 on 2024-06-06 21:01

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Jumbotron",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=128)),
                ("filename", models.CharField(max_length=128)),
                (
                    "jumbotron_type",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "Video"), (1, "Image")]
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "home_jumbotron",
            },
        ),
    ]
