# Generated by Django 5.0.7 on 2024-08-04 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Jumbotron",
        ),
    ]
