# Generated by Django 4.1.5 on 2023-03-03 21:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='Url',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pattern', models.CharField(help_text="Case-sensitive. A missing trailing slash does also match to files which start with the name of the pattern, e.g., '/admin' matches /admin.html too. Some major search engines allow an asterisk (*) as a wildcard and a dollar sign ($) to match the end of the URL, e.g., '/*.jpg$'.", max_length=255, verbose_name='pattern')),
            ],
            options={
                'verbose_name': 'url',
                'verbose_name_plural': 'url',
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('robot', models.CharField(help_text="This should be a user agent string like 'Googlebot'. Enter an asterisk (*) for all user agents. For a full list look at the <a target=_blank href='http://www.robotstxt.org/db.html'> database of Web Robots</a>.", max_length=255, verbose_name='robot')),
                ('crawl_delay', models.DecimalField(blank=True, decimal_places=1, help_text="Between 0.1 and 99.0. This field is supported by some search engines and defines the delay between successive crawler accesses in seconds. If the crawler rate is a problem for your server, you can set the delay up to 5 or 10 or a comfortable value for your server, but it's suggested to start with small values (0.5-1), and increase as needed to an acceptable value for your server. Larger delay values add more delay between successive crawl accesses and decrease the maximum crawl rate to your web server.", max_digits=3, null=True, verbose_name='crawl delay')),
                ('allowed', models.ManyToManyField(blank=True, help_text='The URLs which are allowed to be accessed by bots.', related_name='allowed', to='robots.url', verbose_name='allowed')),
                ('disallowed', models.ManyToManyField(blank=True, help_text='The URLs which are not allowed to be accessed by bots.', related_name='disallowed', to='robots.url', verbose_name='disallowed')),
                ('sites', models.ManyToManyField(to='sites.site', verbose_name='sites')),
            ],
            options={
                'verbose_name': 'rule',
                'verbose_name_plural': 'rules',
            },
        ),
    ]
