# Generated by Django 5.0 on 2024-02-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CodebuildJob",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "build_status",
                    models.PositiveSmallIntegerField(
                        choices=[(0, "IN_REVIEW"), (2, "FAILED"), (1, "SUCCEEDED")]
                    ),
                ),
                ("job", models.CharField(max_length=128)),
                ("logs", models.CharField(max_length=256)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                ("end_time", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "codebuild_job",
            },
        ),
    ]
