# Generated by Django 5.0 on 2024-02-20 08:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="codebuildjob",
            old_name="job",
            new_name="project",
        ),
    ]
