# Generated by Django 5.0 on 2024-02-20 10:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0002_rename_job_codebuildjob_project"),
    ]

    operations = [
        migrations.AddField(
            model_name="codebuildjob",
            name="branch",
            field=models.CharField(default="rev/heads/master", max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="codebuildjob",
            name="build_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (2, "FAILED"),
                    (0, "IN_PROGRESS"),
                    (3, "STOPPED"),
                    (1, "SUCCEEDED"),
                ],
                default=0,
            ),
        ),
    ]
