# Generated by Django 5.0 on 2024-02-20 13:45

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0003_codebuildjob_branch_alter_codebuildjob_build_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodebuildProject",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("project", models.CharField(max_length=128)),
            ],
            options={
                "db_table": "codebuild_project",
            },
        ),
        migrations.AlterField(
            model_name="codebuildjob",
            name="build_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (3, "STOPPED"),
                    (1, "SUCCEEDED"),
                    (0, "IN_PROGRESS"),
                    (2, "FAILED"),
                ],
                default=0,
            ),
        ),
    ]
