# Generated by Django 5.0 on 2024-02-20 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0004_codebuildproject_alter_codebuildjob_build_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="codebuildproject",
            name="last_successful_build",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
