# Generated by Django 5.0 on 2024-02-20 13:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0005_codebuildproject_last_successful_build"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codebuildjob",
            name="build_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (3, "STOPPED"),
                    (2, "FAILED"),
                    (0, "IN_PROGRESS"),
                    (1, "SUCCEEDED"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="codebuildjob",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="jobs",
                to="system.codebuildproject",
            ),
        ),
    ]
