# Generated by Django 5.0 on 2024-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0006_alter_codebuildjob_build_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codebuildjob",
            name="build_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (0, "IN_PROGRESS"),
                    (2, "FAILED"),
                    (1, "SUCCEEDED"),
                    (3, "STOPPED"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="codebuildproject",
            name="id",
            field=models.CharField(
                editable=False, max_length=128, primary_key=True, serialize=False
            ),
        ),
    ]
