# Generated by Django 5.0 on 2024-03-16 18:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0007_alter_codebuildjob_build_status_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codebuildjob",
            options={"get_latest_by": "-end_time"},
        ),
        migrations.AlterField(
            model_name="codebuildjob",
            name="build_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (3, "STOPPED"),
                    (2, "FAILED"),
                    (1, "SUCCEEDED"),
                    (0, "IN_PROGRESS"),
                ],
                default=0,
            ),
        ),
    ]
