# Generated by Django 5.0 on 2024-04-08 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0008_alter_codebuildjob_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="codebuildjob",
            options={"get_latest_by": "-start_time", "ordering": ("-start_time",)},
        ),
        migrations.AlterField(
            model_name="codebuildjob",
            name="build_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (3, "STOPPED"),
                    (0, "IN_PROGRESS"),
                    (2, "FAILED"),
                    (1, "SUCCEEDED"),
                ],
                default=0,
            ),
        ),
    ]
