# Generated by Django 5.0 on 2024-05-14 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0009_alter_codebuildjob_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodePipelineProject",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pipeline", models.CharField(max_length=128)),
                ("topic_arn", models.CharField(max_length=256)),
                ("last_successful_build", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "codepipeline_project",
            },
        ),
        migrations.AlterField(
            model_name="codebuildjob",
            name="build_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (3, "STOPPED"),
                    (0, "IN_PROGRESS"),
                    (1, "SUCCEEDED"),
                    (2, "FAILED"),
                ],
                default=0,
            ),
        ),
        migrations.CreateModel(
            name="CodePipelineState",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("notification_rule_arn", models.CharField(max_length=128)),
                ("state", models.CharField(max_length=64)),
                ("start_time", models.DateTimeField(blank=True, null=True)),
                (
                    "pipeline_execution_attempt",
                    models.PositiveSmallIntegerField(default=0),
                ),
                ("payload", models.CharField(max_length=1024)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="states",
                        to="system.codepipelineproject",
                    ),
                ),
            ],
            options={
                "db_table": "codepipeline_state",
            },
        ),
    ]
