# Generated by Django 5.0 on 2024-05-14 04:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0010_codepipelineproject_alter_codebuildjob_build_status_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codepipelineproject",
            name="last_successful_build",
        ),
        migrations.AlterField(
            model_name="codebuildjob",
            name="build_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "SUCCEEDED"),
                    (2, "FAILED"),
                    (3, "STOPPED"),
                    (0, "IN_PROGRESS"),
                ],
                default=0,
            ),
        ),
    ]
