# Generated by Django 5.0 on 2024-05-14 04:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0011_remove_codepipelineproject_last_successful_build_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="codepipelinestate",
            old_name="project",
            new_name="pipeline",
        ),
        migrations.AlterField(
            model_name="codebuildjob",
            name="build_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (3, "STOPPED"),
                    (2, "FAILED"),
                    (1, "SUCCEEDED"),
                    (0, "IN_PROGRESS"),
                ],
                default=0,
            ),
        ),
    ]
