# Generated by Django 5.0 on 2024-05-14 05:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0012_rename_project_codepipelinestate_pipeline_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codebuildjob",
            name="build_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (2, "FAILED"),
                    (3, "STOPPED"),
                    (1, "SUCCEEDED"),
                    (0, "IN_PROGRESS"),
                ],
                default=0,
            ),
        ),
        migrations.CreateModel(
            name="CodePipelineStatePayload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("payload", models.CharField(max_length=1024)),
                (
                    "state",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payloads",
                        to="system.codepipelinestate",
                    ),
                ),
            ],
            options={
                "db_table": "codepipeline_state_payload",
            },
        ),
    ]
