# Generated by Django 5.0 on 2024-05-17 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0013_alter_codebuildjob_build_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="codepipelinestate",
            name="event_id",
            field=models.UUIDField(
                default="e9af876f-2d15-409f-a8fb-8daa362cec7a", editable=False
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="codebuildjob",
            name="build_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (3, "STOPPED"),
                    (0, "IN_PROGRESS"),
                    (1, "SUCCEEDED"),
                    (2, "FAILED"),
                ],
                default=0,
            ),
        ),
        migrations.DeleteModel(
            name="CodePipelineStatePayload",
        ),
    ]
