# Generated by Django 5.0 on 2024-05-17 17:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0014_codepipelinestate_event_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codebuildjob",
            name="build_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "SUCCEEDED"),
                    (3, "STOPPED"),
                    (0, "IN_PROGRESS"),
                    (2, "FAILED"),
                ],
                default=0,
            ),
        ),
    ]
