# Generated by Django 5.0 on 2024-05-17 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0015_alter_codebuildjob_build_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="CodePipelineRun",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=128,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pipeline", models.CharField(max_length=128)),
                ("topic_arn", models.CharField(max_length=256)),
                ("run_date", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "codepipeline_project_run",
            },
        ),
        migrations.RemoveField(
            model_name="codepipelinestate",
            name="event_id",
        ),
        migrations.AlterField(
            model_name="codebuildjob",
            name="build_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (3, "STOPPED"),
                    (1, "SUCCEEDED"),
                    (2, "FAILED"),
                    (0, "IN_PROGRESS"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="codepipelinestate",
            name="pipeline",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="states",
                to="system.codepipelinerun",
            ),
        ),
        migrations.DeleteModel(
            name="CodePipelineProject",
        ),
    ]
