# Generated by Django 5.0 on 2024-05-17 18:42

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("system", "0016_codepipelinerun_remove_codepipelinestate_event_id_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="codebuildjob",
            name="build_status",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (2, "FAILED"),
                    (3, "STOPPED"),
                    (0, "IN_PROGRESS"),
                    (1, "SUCCEEDED"),
                ],
                default=0,
            ),
        ),
        migrations.AlterField(
            model_name="codepipelinestate",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
