# Generated by Django 5.0.6 on 2024-06-05 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("system", "0018_merge_20240520_1927"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="codepipelinestate",
            name="pipeline",
        ),
        migrations.DeleteModel(
            name="CodebuildJob",
        ),
        migrations.DeleteModel(
            name="CodebuildProject",
        ),
        migrations.DeleteModel(
            name="CodePipelineRun",
        ),
        migrations.DeleteModel(
            name="CodePipelineState",
        ),
    ]
