# Generated by Django 5.0 on 2024-06-06 21:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("maps", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DivesiteTagOption",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("tag", models.CharField(max_length=100, unique=True)),
            ],
            options={
                "db_table": "divesite_tag_option",
            },
        ),
        migrations.CreateModel(
            name="Divesite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("url", models.URLField(blank=True, db_index=True, max_length=255)),
                ("lat", models.DecimalField(decimal_places=9, max_digits=15)),
                ("location", models.CharField(max_length=128)),
                ("long", models.DecimalField(decimal_places=9, max_digits=15)),
                ("aws_id", models.CharField(blank=True, max_length=10)),
                ("is_active", models.BooleanField(default=True)),
                ("query_weather", models.BooleanField(default=True)),
                (
                    "difficulty",
                    models.PositiveSmallIntegerField(
                        choices=[
                            (0, "Beginner"),
                            (10, "Intermediate"),
                            (20, "Advanced"),
                        ]
                    ),
                ),
                (
                    "region",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maps.region",
                    ),
                ),
            ],
            options={
                "db_table": "divesites",
            },
        ),
        migrations.CreateModel(
            name="DivesiteBanner",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("banner", models.CharField(max_length=128)),
                (
                    "divesite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="banners",
                        to="divesites.divesite",
                    ),
                ),
            ],
            options={
                "db_table": "divesite_banner",
            },
        ),
        migrations.CreateModel(
            name="DivesiteCheckin",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("visibility", models.PositiveSmallIntegerField(default=0)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1
                    ),
                ),
                ("temp_c", models.FloatField(default=0.0)),
                ("review", models.TextField(default="")),
                ("is_anonymous", models.BooleanField(default=False)),
                ("checkin_date", models.DateField(auto_now_add=True)),
                (
                    "divesite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="divesites.divesite",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "divesite_checkin",
                "unique_together": {("user", "divesite", "checkin_date")},
            },
        ),
        migrations.CreateModel(
            name="DivesiteFavorite",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_favorite", models.BooleanField(default=True)),
                (
                    "divesite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="followers",
                        to="divesites.divesite",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="favorites",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "divesite_favorite",
            },
        ),
        migrations.CreateModel(
            name="DivesiteCheckinThank",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("is_thanked", models.BooleanField(default=True)),
                (
                    "divesite_checkin",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thanks",
                        to="divesites.divesitecheckin",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="thanks",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "divesite_checkin_thank",
                "unique_together": {("user", "divesite_checkin")},
            },
        ),
        migrations.CreateModel(
            name="DivesiteDailyStats",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("temp_c", models.FloatField()),
                ("visibility", models.PositiveSmallIntegerField()),
                ("stats_date", models.DateField()),
                (
                    "divesite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to="divesites.divesite",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "divesite_daily_stats",
                "unique_together": {("user", "divesite", "stats_date")},
            },
        ),
        migrations.CreateModel(
            name="DivesiteReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("review", models.TextField()),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)]
                    ),
                ),
                ("temp_c", models.FloatField(default=0.0)),
                ("visibility", models.FloatField(default=0.0)),
                ("review_date", models.DateField(auto_now_add=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "divesite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="divesites.divesite",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "divesite_review",
                "unique_together": {("user", "divesite", "review_date")},
            },
        ),
        migrations.CreateModel(
            name="DivesiteTag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "divesite",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="divesites.divesite",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="divesites.divesitetagoption",
                    ),
                ),
            ],
            options={
                "db_table": "divesite_tag",
                "unique_together": {("divesite", "tag")},
            },
        ),
    ]
