# Generated by Django 4.1.5 on 2023-03-31 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesite',
            name='difficulty',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Beginner'), (10, 'Intermediate'), (20, 'Advanced')], default=0),
            preserve_default=False,
        ),
    ]
