# Generated by Django 4.1.5 on 2023-03-31 00:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0002_divesite_difficulty'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivesiteBanner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('banner', models.CharField(max_length=128)),
                ('divesite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='divesites.divesite')),
            ],
            options={
                'db_table': 'divesite_banner',
            },
        ),
    ]
