# Generated by Django 4.1.5 on 2023-03-31 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0003_divesitebanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesite',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='divesite',
            name='url',
            field=models.URLField(db_index=True, max_length=255),
        ),
    ]
