# Generated by Django 4.1.5 on 2023-03-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0004_divesite_is_active_alter_divesite_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesite',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
