# Generated by Django 4.1.5 on 2023-03-31 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0005_divesite_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divesite',
            name='url',
            field=models.URLField(blank=True, db_index=True, max_length=255),
        ),
    ]
