# Generated by Django 4.1.7 on 2023-04-01 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0006_alter_divesite_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divesite',
            name='lat',
            field=models.DecimalField(decimal_places=13, max_digits=9),
        ),
        migrations.AlterField(
            model_name='divesite',
            name='long',
            field=models.DecimalField(decimal_places=13, max_digits=9),
        ),
    ]
