# Generated by Django 4.1.7 on 2023-04-14 18:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divesites', '0007_alter_divesite_lat_alter_divesite_long'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesitereview',
            name='review_date',
            field=models.DateField(auto_now_add=True, default='2022-01-01'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='divesitereview',
            unique_together={('user', 'divesite', 'review_date')},
        ),
    ]
