# Generated by Django 4.1.7 on 2023-04-14 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divesites', '0008_divesitereview_review_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivesiteFollowing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_following', models.BooleanField(default=True)),
                ('divesite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='divesites.divesite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'divesite_following',
            },
        ),
    ]
