# Generated by Django 4.1.7 on 2023-04-17 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0010_divesitefavorite_delete_divesitefollowing'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesite',
            name='aws_id',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='divesitebanner',
            name='divesite',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banners', to='divesites.divesite'),
        ),
    ]
