# Generated by Django 4.1.7 on 2023-04-17 20:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divesites', '0011_divesite_aws_id_alter_divesitebanner_divesite'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivesiteDailyStats',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('temp_c', models.FloatField()),
                ('visibility', models.PositiveSmallIntegerField()),
                ('stats_date', models.DateField(auto_now_add=True)),
                ('divesite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='divesites.divesite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'divesite_daily_stats',
            },
        ),
    ]
