# Generated by Django 4.1.7 on 2023-04-17 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0012_divesitedailystats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divesitedailystats',
            name='stats_date',
            field=models.DateField(),
        ),
    ]
