# Generated by Django 4.1.7 on 2023-04-18 01:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
        ('divesites', '0013_alter_divesitedailystats_stats_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesite',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.region'),
        ),
    ]
