# Generated by Django 4.1.7 on 2023-04-18 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0014_divesite_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesite',
            name='query_weather',
            field=models.BooleanField(default=True),
        ),
    ]
