# Generated by Django 4.1.7 on 2023-04-18 21:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divesites', '0015_divesite_query_weather'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='divesitedailystats',
            unique_together={('user', 'divesite', 'stats_date')},
        ),
    ]
