# Generated by Django 4.1.7 on 2023-04-19 02:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divesites', '0016_alter_divesitedailystats_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesitereview',
            name='temp_c',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='divesitereview',
            name='visibility',
            field=models.FloatField(default=0.0),
        ),
        migrations.CreateModel(
            name='DivesiteCheckin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('checkin_date', models.DateField(auto_now_add=True)),
                ('divesite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to='divesites.divesite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkins', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'divesite_checkin',
                'unique_together': {('user', 'divesite', 'checkin_date')},
            },
        ),
    ]
