# Generated by Django 4.1.7 on 2023-04-22 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0017_divesitereview_temp_c_divesitereview_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divesitecheckin',
            name='note',
            field=models.TextField(default=''),
        ),
    ]
