# Generated by Django 4.1.7 on 2023-04-22 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0018_alter_divesitecheckin_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesitecheckin',
            name='temp_c',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='divesitecheckin',
            name='visibility',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
