# Generated by Django 4.1.7 on 2023-04-28 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divesites', '0019_divesitecheckin_temp_c_divesitecheckin_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivesiteCheckinThank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_thanked', models.BooleanField(default=True)),
                ('divesite_checkin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanks', to='divesites.divesitecheckin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thanks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'divesite_checkin_thank',
                'unique_together': {('user', 'divesite_checkin')},
            },
        ),
    ]
