# Generated by Django 4.2.5 on 2023-10-13 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divesites', '0020_divesitecheckinthank'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivesiteTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100)),
                ('divesite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='divesites.divesite')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'divesite_tag',
                'unique_together': {('divesite', 'tag')},
            },
        ),
    ]
