# Generated by Django 4.2.5 on 2023-10-13 19:20

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0021_divesitetag'),
    ]

    operations = [
        migrations.CreateModel(
            name='DivesiteTagOption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tag', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'divesite_tag_option',
            },
        ),
        migrations.AlterField(
            model_name='divesitetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='divesites.divesitetagoption'),
        ),
    ]
