# Generated by Django 4.2.5 on 2023-10-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0022_divesitetagoption_alter_divesitetag_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesite',
            name='location',
            field=models.CharField(default='San Diego, CA', max_length=128),
            preserve_default=False,
        ),
    ]
