# Generated by Django 4.2.5 on 2023-10-31 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0023_divesite_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='divesitecheckin',
            old_name='note',
            new_name='review',
        ),
        migrations.AddField(
            model_name='divesitecheckin',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
            preserve_default=False,
        ),
    ]
