# Generated by Django 4.2.5 on 2023-10-31 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0024_rename_note_divesitecheckin_review_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='divesitecheckin',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
    ]
