# Generated by Django 4.2.5 on 2023-11-21 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('divesites', '0025_alter_divesitecheckin_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='divesitecheckin',
            name='is_anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
