# Generated by Django 4.1.7 on 2023-05-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='image',
            new_name='filename',
        ),
        migrations.RemoveField(
            model_name='media',
            name='guid',
        ),
        migrations.AddField(
            model_name='media',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2020-01-01'),
            preserve_default=False,
        ),
    ]
