# Generated by Django 4.2.5 on 2023-10-03 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0002_rename_image_media_filename_remove_media_guid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='guid',
        ),
    ]
