# Generated by Django 4.2.5 on 2023-10-03 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('galleries', '0003_remove_album_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
