version: 0.2

env:
  shell: bash
  variables:
    SETTINGS_PATH: "/dev/null"
phases:
  install:
    commands:
      - apt update -y
      - apt install -y python3-venv

  pre_build:
    commands:
      - python3 -m venv /tmp/env
      - source /tmp/env/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install --upgrade awscli

  #install:
    #If you use the Ubuntu standard image 2.0 or later, you must specify runtime-versions.
    #If you specify runtime-versions and use an image other than Ubuntu standard image 2.0, the build fails.
    #runtime-versions:
      # name: version
      # name: version
    #commands:
      # - command
      # - command
  build:
    commands:
      - source /tmp/env/bin/activate
      - npm install
      - npm run build
  post_build:
    commands:
      - source /tmp/env/bin/activate
      - pytest
      - flake8 --exit-zero --exclude=migrations --max-line-length=100 --format=html --htmldir=flake-report scuba/ > pep8.log
      - aws s3 sync ./coverage s3://scubamob-pipeline-reports/${CODEBUILD_BUILD_ARN}/coverage/
      - aws s3 sync ./coverage s3://scubamob-pipeline-reports/${CODEBUILD_BUILD_ARN}/flake-report/

reports:
  unittests:
    files:
      - 'test_*.xml'
  pep8:
    files:
      - 'pep8.log'
  codecoverage:
    files:
      - 'coverage.xml'
    file-format: 'COBERTURAXML'

cache:
  paths:
     - './node_modules/**/*'
     - '/tmp/env/**/*'

artifacts:
  files:
    - manage.py
    - requirements.txt
    - appspec.yml
    - scuba/**/*
    - static/**/*
    - scripts/**/*
    - node_modules/**/*
    - templates/**/*
