version: 0.2

env:
  shell: bash
phases:
  install:
    commands:
      - apt update -y
      - apt install -y python3-venv

  pre_build:
    commands:
      - python3 -m venv /tmp/env
      - mkdir -p /scuba/system
      - aws s3 cp s3://scubamob-prod/system/settings.py /scuba/system/settings.py
      - source /tmp/env/bin/activate
      - pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install --upgrade awscli

  build:
    commands:
      - source /tmp/env/bin/activate
      - npm install
      - npm run build
      - python3 manage.py compress --force
      - python3 manage.py collectstatic --noinput
  post_build:
    commands:
      - source /tmp/env/bin/activate
      - pytest
      - flake8 --exit-zero --exclude=migrations --max-line-length=100 --format=html --htmldir=flake-report scuba/ > pep8.log
      - aws s3 sync ./coverage s3://scubamob-deploy/builds/${CODEBUILD_BUILD_ARN}/coverage/
      - aws s3 sync ./flake-report s3://scubamob-deploy/builds/${CODEBUILD_BUILD_ARN}/flake-report/
      - aws s3 sync ./static/CACHE s3://scubamob-prod/static/CACHE/
      - aws s3 sync ./static/bootstrap-icons s3://scubamob-prod/static/bootstrap-icons/
      - aws s3 sync ./static/images s3://scubamob-prod/static/images/
      - aws s3 sync ./static/admin s3://scubamob-prod/static/admin/

reports:
  unittests:
    files:
      - 'test_*.xml'
  pep8:
    files:
      - 'pep8.log'
  codecoverage:
    files:
      - 'coverage.xml'
    file-format: 'COBERTURAXML'

cache:
  paths:
     - './node_modules/**/*'
     - '/tmp/env/**/*'

artifacts:
  files:
    - manage.py
    - requirements.txt
    - appspec.yml
    - scuba/**/*
    - scripts/**/*
    - static/**/*
    - node_modules/**/*
    - templates/**/*
