# Generated by Django 4.1.7 on 2023-04-18 01:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'regions',
                'unique_together': {('name', 'region', 'country')},
            },
        ),
    ]
