# Generated by Django 5.0 on 2024-02-12 00:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("region", models.CharField(max_length=100)),
                ("country", models.CharField(max_length=100)),
            ],
            options={
                "db_table": "regions",
                "unique_together": {("name", "region", "country")},
            },
        ),
    ]
