# Generated by Django 4.1.7 on 2023-04-18 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.CharField(max_length=100),
        ),
    ]
