# Generated by Django 4.1.7 on 2023-04-10 15:19

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('region', models.CharField(max_length=128)),
                ('country', models.CharField(max_length=128)),
                ('lat', models.DecimalField(decimal_places=9, max_digits=15)),
                ('long', models.DecimalField(decimal_places=9, max_digits=15)),
                ('tz_id', models.CharField(max_length=64)),
                ('localtime', models.PositiveIntegerField()),
                ('data', models.JSONField(max_length=128)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'weather',
            },
        ),
    ]
