# Generated by Django 4.1.7 on 2023-04-11 01:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_rename_long_weather_lng'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherPostalCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('postal_code', models.CharField(max_length=15)),
                ('weather', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postal_codes', to='weather.weather')),
            ],
            options={
                'db_table': 'weather_postal_code',
            },
        ),
    ]
